# Generated by Django 3.1.3 on 2020-11-19 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForexProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('usd', models.FloatField()),
                ('eur', models.FloatField()),
                ('gbp', models.FloatField()),
                ('aud', models.FloatField()),
                ('lastupdated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
