# Generated by Django 3.1.3 on 2020-11-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForexProvider', '0005_auto_20201123_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexprovider',
            name='aud',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ForexProvider.currency_chart'),
        ),
        migrations.AddField(
            model_name='forexprovider',
            name='eur',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ForexProvider.currency_chart'),
        ),
        migrations.AddField(
            model_name='forexprovider',
            name='gbp',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ForexProvider.currency_chart'),
        ),
        migrations.AddField(
            model_name='forexprovider',
            name='usd',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ForexProvider.currency_chart'),
        ),
    ]
