# Generated by Django 3.1.3 on 2020-11-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForexProvider', '0006_auto_20201123_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_chart',
            name='name',
            field=models.CharField(default='chart', max_length=100),
        ),
    ]
