# Generated by Django 3.1.3 on 2020-11-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForexProvider', '0010_auto_20201123_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency_chart',
            name='id',
        ),
        migrations.AlterField(
            model_name='currency_chart',
            name='name',
            field=models.CharField(default='chart', max_length=100, primary_key=True, serialize=False),
        ),
    ]
