# Generated by Django 3.1.3 on 2020-11-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForexProvider', '0011_auto_20201123_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexprovider',
            name='aud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aud', to='ForexProvider.currency_chart'),
        ),
        migrations.AlterField(
            model_name='forexprovider',
            name='eur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eur', to='ForexProvider.currency_chart'),
        ),
        migrations.AlterField(
            model_name='forexprovider',
            name='gbp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gbp', to='ForexProvider.currency_chart'),
        ),
        migrations.AlterField(
            model_name='forexprovider',
            name='usd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usd', to='ForexProvider.currency_chart'),
        ),
    ]
