# Generated by Django 3.1.3 on 2020-11-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForexProvider', '0012_auto_20201123_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forexprovider',
            name='aud',
        ),
        migrations.RemoveField(
            model_name='forexprovider',
            name='eur',
        ),
        migrations.RemoveField(
            model_name='forexprovider',
            name='gbp',
        ),
        migrations.RemoveField(
            model_name='forexprovider',
            name='usd',
        ),
    ]
