# Generated by Django 3.1.3 on 2020-11-24 06:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_Cash_High',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.FloatField()),
                ('eur', models.FloatField()),
                ('gbp', models.FloatField()),
                ('aud', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Buy_Cash_Low',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.FloatField()),
                ('eur', models.FloatField()),
                ('gbp', models.FloatField()),
                ('aud', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Currency_Chart',
            fields=[
                ('name', models.CharField(default='chart', max_length=100, primary_key=True, serialize=False)),
                ('buy_cash', models.FloatField(default=1)),
                ('buy_card', models.FloatField(default=1)),
                ('sell_cash', models.FloatField(default=1)),
                ('sell_card', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ForexProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ForexProvider', max_length=100)),
                ('site', models.URLField()),
                ('usd', models.FloatField()),
                ('eur', models.FloatField()),
                ('gbp', models.FloatField()),
                ('aud', models.FloatField()),
                ('lastupdated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
