# Generated by Django 3.1.3 on 2020-11-26 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForexProvider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies_list',
            name='inr',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='forexprovider',
            name='inr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inr', to='ForexProvider.currency_chart'),
        ),
    ]
