# Generated by Django 3.1.3 on 2020-11-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForexProvider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexprovider',
            name='name',
            field=models.CharField(default='ForexProvider', max_length=100),
        ),
        migrations.AlterField(
            model_name='forexprovider',
            name='site',
            field=models.URLField(),
        ),
    ]
