# Generated by Django 3.1.3 on 2020-11-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForexProvider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_chart',
            name='name',
            field=models.CharField(default='chart', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
