# Generated by Django 3.1.3 on 2020-11-20 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForexProvider', '0002_auto_20201120_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_Cash_High',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.FloatField()),
                ('eur', models.FloatField()),
                ('gbp', models.FloatField()),
                ('aud', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Buy_Cash_Low',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.FloatField()),
                ('eur', models.FloatField()),
                ('gbp', models.FloatField()),
                ('aud', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
