# Generated by Django 3.1.3 on 2020-11-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForexProvider', '0002_auto_20201124_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexprovider',
            name='aud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aud', to='ForexProvider.currency_chart'),
        ),
        migrations.AddField(
            model_name='forexprovider',
            name='gbp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gbp', to='ForexProvider.currency_chart'),
        ),
    ]
