# Generated by Django 3.1.3 on 2020-11-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cur',
            name='rate',
            field=models.IntegerField(default=1),
        ),
    ]
