# Generated by Django 3.1.3 on 2020-11-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20201116_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cur',
            name='rate',
        ),
        migrations.AddField(
            model_name='cur',
            name='rate1',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='cur',
            name='rate2',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='cur',
            name='rate3',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='cur',
            name='rate4',
            field=models.FloatField(default=1),
        ),
    ]
