# Generated by Django 3.1.3 on 2020-11-18 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20201117_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='cur',
            name='lastupdated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
