# Generated by Django 3.1.3 on 2020-11-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_compareoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareoutput',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
